version: "3.9"

networks:
  monitoring:

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - .:/code
    links:
      - web_server

  web_server:
    build: ./web_server

  fluentd:
    build: ./fluentd
    ports:
      - 24224:24224

  influxdb2:
    image: influxdb:2.1.1
    volumes:
      - influxdb2:/var/lib/influxdb2
    environment:
    ports:
      - 8086:8086
    
volumes:
  influxdb2: